[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps = 
	m5stack/M5Unified@^0.2.2
	fastled/FastLED@^3.9.4
